language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: B86BcJ9fD5VzX4bvpK0l/f+9GnMLQdUbpzTQyoO7n9EGnMZ5PaB36nryLH/gf5JSmI7AZIZzUG4gbRWhRoGJNIMCoOZAJEXqtIJGFKA5BoHoSSRWBbY5+NKB5waB77cF7ZVx7PT7i3bqTM6aFw3k8JVJ1MZGroQiaDkMZlxwWqYUBjftu5pKwhzWTJpikRVPmkmJNoaBXkak13Vo/KX7SClb/EmN2i16QLu1wqouQ/Z6U4ViPxPCB9gRsLBNfabLvVs/Hqn5QIKTuSA8uDwGRmMbbwRQoEKsnmBo1TyUQgB+mJAZtSgOqhGUrvZXA2w4SVIcVqakkkmCqfOA04RbxnXcEjDxUibrjjcqEOap8Ekko2Vr7I+Tkpfv1wrZiBaUHdsMHiuLawWORn1uZOJpv7fADyw730jbLaWKwA1DaATNJKgaTkeH8JpmKTLpEEMMIyjqMnRHerAHNbxQXyn1CGaWSF/uf3A/hImdl1IvqP9rHAlZiGX4eUKy0Oo0LRBNvButo6q1qKprcJk3MYetR8r9iRPTwEOmCPxMuCLVzWTUtYJdJlxNK7SolVttfgn7lxUd85D1DsQIb/b7iqnEwwmARKFmoETAMH4Q2GAnbYlTCOM8T/QKE3BoP3WHWsHFLNiGXnZPkU+Pv8R0pwWqvreyK4b2pMNhItbWXZrqldo=
  app: evening-retreat-40915
  on:
    repo: wdi-milieu/milieu-user
